-- =========================================================================
-- Twodigit.io - Supabase Schema Migration: Donations Table
-- =========================================================================
-- Run this in your Supabase Dashboard: SQL Editor -> New Query -> Run
-- =========================================================================

CREATE TABLE IF NOT EXISTS public.donations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT UNIQUE NOT NULL,
    amount NUMERIC NOT NULL,
    donor_name TEXT DEFAULT 'Anonim',
    message TEXT DEFAULT '',
    media_url TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Indices for performance
CREATE INDEX IF NOT EXISTS idx_donations_created_at ON public.donations(created_at);
CREATE INDEX IF NOT EXISTS idx_donations_order_id ON public.donations(order_id);

-- Enable Row Level Security (RLS)
ALTER TABLE public.donations ENABLE ROW LEVEL SECURITY;

-- Allow public read access (for overlays & milestone queries)
CREATE POLICY "Allow public read access to donations" 
ON public.donations FOR SELECT 
USING (true);

-- Allow service role full access (insert / update / delete)
CREATE POLICY "Allow service role full access to donations" 
ON public.donations FOR ALL 
TO service_role 
USING (true)
WITH CHECK (true);
